# Generated by Django 5.1.4 on 2025-01-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdiSoyadi', models.CharField(max_length=50)),
                ('Bransi', models.CharField(max_length=11)),
                ('Sinifi', models.CharField(max_length=12, null='True')),
                ('Aciklama', models.CharField(max_length=250)),
            ],
        ),
    ]
